version: 2
jobs:
  build:
    working_directory: ~/build
    docker:
      - image: fyndiq/python-alpine-kafka:latest
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements/common.txt -r requirements/test.txt
      - run:
          name: Running lint
          command: make lint
      - run:
          name: Running tests
          command: make unit-test
      - store_test_results:
          path: /tmp/test-results
workflows:
  version: 2
  build:
    jobs:
      - build