version: 2
references:
  container_config: &container_config
    docker:
      - image: fyndiq/circleci-python-gcloudsdk:latest

  checkout_submodules: &checkout_submodules
    run:
      name: Checkout submodules
      command: |
        git submodule sync
        git submodule update --init --remote

  setup_env: &setup_env
    run:
      name: Setup environment
      command: |
        echo 'export APP_NAME=$CIRCLE_PROJECT_REPONAME' >> $BASH_ENV
        # Name of the deployment from which a pod will be selected to run
        # the smoke tests.
        #
        # All deployments that belongs to the same name will also be rolled back
        # on failures.
        #
        # Default we use the same name as the repository. Only override this
        # if the app label in the deployments doesn't match the repo name.
        echo 'export K8S_APP_NAME=$APP_NAME' >> $BASH_ENV

  gcloud_setup: &gcloud_setup
    run:
      name: Setup Google Cloud SDK
      command: ./scripts/ci-cd/setup-gcloud.sh

jobs:
  build:
    <<: *container_config
    steps:
      - checkout
      - *checkout_submodules
      - *setup_env
      - setup_remote_docker
      - *gcloud_setup
      - run:
          name: Run lint
          command: ./scripts/ci-cd/run.sh "make lint"
      - run:
          name: Run unit tests
          command: ./scripts/ci-cd/run.sh "make unit-test"
      - run:
          name: Publish image
          command: ./scripts/ci-cd/publish.sh

workflows:
  version: 2
  build_deploy_and_test:
    jobs:
      - build:
          context: org-global